# .streamlit/secrets.toml
NVIDIA_API_KEY = "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"
DATABASE_URL = "postgresql://neondb_owner:npg_kWpADsmyM19q@ep-orange-heart-ahpun5ah-pooler.c-3.us-east-1.aws.neon.tech:5432/neondb?sslmode=require"